Repository Team-NBK-04/sajo-chamchi, pull requests merged in 2023-10, with the labels that each got.

#10 Design/homepage
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_view.xml
Labels: design

#11 Feature/splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/team4/sajochamchi/ui/activity/SplashActivity.kt
  app/src/main/res/anim/anim_splash_imageview.xml
  app/src/main/res/anim/anim_splash_in_down.xml
  app/src/main/res/anim/anim_splash_out_top.xml
  app/src/main/res/layout/activity_splash.xml
Labels: enhancement

#13 Design/search
  .idea/misc.xml
  app/src/main/res/drawable/background_blackstroke_board.xml
  app/src/main/res/drawable/background_search_board.xml
  app/src/main/res/drawable/img_clear.png
  app/src/main/res/drawable/img_down_arrow.png
  app/src/main/res/drawable/img_exclamation.png
  app/src/main/res/drawable/img_pencil.png
  app/src/main/res/drawable/img_search_pin.png
  app/src/main/res/drawable/img_search_play.png
  app/src/main/res/drawable/img_up_arrow.png
  app/src/main/res/drawable/item_search.xml
  app/src/main/res/drawable/selector_arrow.xml
  app/src/main/res/drawable/selector_search_screen.xml
  app/src/main/res/layout/fagment_search_item_screen.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_horizontal_string.xml
  app/src/main/res/layout/item_vertical_video.xml
  app/src/main/res/values/dimens.xml
Labels: design

#15 Feature/home
  app/build.gradle
  app/src/main/java/com/team4/sajochamchi/ui/adapter/ChannelAdapter.kt
  app/src/main/java/com/team4/sajochamchi/ui/adapter/HorizontalVideoAdapter.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/HomeFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_horizontal_channel.xml
  app/src/main/res/layout/item_horizontal_video.xml
Labels: design

#20 Feature/dialog
  .idea/gradle.xml
  app/src/main/java/com/team4/sajochamchi/ui/dialog/ViewDetailDialog.kt
  app/src/main/res/layout/dialog_categories.xml
  app/src/main/res/layout/dialog_view_detail.xml
  app/src/main/res/layout/item_selected_categories.xml
  app/src/main/res/layout/item_unselected_categories.xml
Labels: enhancement, design

#21 [DESIGN] : 🎨 이미지 변경
  app/src/main/res/drawable/img_drag_drop.png
  app/src/main/res/layout/item_selected_categories.xml
Labels: design

#22 Feature/home
  app/src/main/res/drawable/background_home_category_button.xml
  app/src/main/res/drawable/background_home_category_button_selected.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_homepage_category_button.xml
Labels: design

#23 Design/mypage
  app/src/main/res/drawable/img_mypage_pencil.png
  app/src/main/res/drawable/img_mypage_wave.png
  app/src/main/res/drawable/img_pencil.png
  app/src/main/res/layout/fragment_my_page.xml
Labels: design

#24 Feautre/mypage
  app/src/main/java/com/team4/sajochamchi/data/repository/TotalRepository.kt
  app/src/main/java/com/team4/sajochamchi/data/repository/TotalRepositoryImpl.kt
  app/src/main/java/com/team4/sajochamchi/data/sharedpreferences/MySharedPreferences.kt
  app/src/main/java/com/team4/sajochamchi/ui/adapter/SaveVideoAdapter.kt
  app/src/main/java/com/team4/sajochamchi/ui/dialog/EditDialog.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/MypageViewModel.kt
  app/src/main/res/drawable/background_input_text.xml
  app/src/main/res/layout/dialog_edit.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: enhancement

#25 Feature/search
  app/src/main/java/com/team4/sajochamchi/ui/fragment/SearchFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: enhancement

#27 Feature/dialog
  app/src/main/java/com/team4/sajochamchi/data/dao/ItemDao.kt
  app/src/main/java/com/team4/sajochamchi/data/repository/TotalRepository.kt
  app/src/main/java/com/team4/sajochamchi/data/repository/TotalRepositoryImpl.kt
  app/src/main/java/com/team4/sajochamchi/ui/adapter/SelectedCategoriesAdpter.kt
  app/src/main/java/com/team4/sajochamchi/ui/adapter/UnselectedCategoriesAdapter.kt
  app/src/main/java/com/team4/sajochamchi/ui/dialog/CategoriesDialog.kt
  app/src/main/java/com/team4/sajochamchi/ui/dialog/ViewDetailDialog.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/HomeFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/MyPageFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/SearchFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/CategoryViewModel.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/ViewDetailViewModel.kt
  app/src/main/res/drawable/background_gradient.xml
  app/src/main/res/drawable/img_favorite.png
  app/src/main/res/drawable/img_unfavorite.png
  app/src/main/res/drawable/recyclerview_divider.xml
  app/src/main/res/drawable/selector_favorite.xml
  app/src/main/res/layout/dialog_categories.xml
  app/src/main/res/layout/dialog_view_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_selected_categories.xml
  app/src/main/res/layout/item_unselected_categories.xml
Labels: enhancement

#28 Feature/category and paging
  app/src/main/java/com/team4/sajochamchi/ui/fragment/HomeFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/CategoryViewModel.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/SearchViewModel.kt
  app/src/main/res/color/selected_highlight.xml
  app/src/main/res/color/selected_highlight_stroke.xml
  app/src/main/res/drawable/background_gradient_bottom.xml
  app/src/main/res/drawable/background_gradient_end.xml
  app/src/main/res/drawable/background_gradient_start.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/region.xml
  app/src/main/res/values/style.xml
Labels: enhancement

#31 Bugfix
  app/src/main/java/com/team4/sajochamchi/ui/fragment/HomeFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/fragment/SearchFragment.kt
  app/src/main/java/com/team4/sajochamchi/ui/viewmodel/CategoryViewModel.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: fix
